name: logly
description: A Very Good Project created by Very Good CLI.
version: 4.1.5+2008
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0
  
dependencies:
  auto_size_text: ^3.0.0
  cached_network_image: ^3.4.1
  dartx: ^1.2.0
  device_info_plus: ^12.3.0
  dotted_border: ^3.1.0
  drift: ^2.22.1
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  flutter_chat_core: ^2.9.0
  flutter_chat_ui: ^2.11.1
  flutter_dotenv: ^6.0.0
  flutter_local_notifications: ^19.5.0
  flutter_native_splash: ^2.4.7
  flutter_riverpod: ^3.2.0
  flutter_secure_storage: ^10.0.0
  flutter_svg: ^2.2.3
  flutter_udid: ^4.1.1
  flyer_chat_text_stream_message: ^2.3.0
  freezed_annotation: ^3.1.0
  gap: ^3.0.1
  go_router: ^17.0.1
  google_sign_in: ^6.2.2
  gpt_markdown: ^1.1.5
  growthbook_sdk_flutter: ^4.1.1
  health: ^13.2.1
  in_app_review: ^2.0.11
  infinite_scroll_pagination: ^5.1.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  logger: ^2.5.0
  lucide_icons_flutter: ^3.1.9
  mixpanel_flutter: ^2.4.4
  package_info_plus: ^9.0.0
  path: ^1.9.0
  path_provider: ^2.1.5
  provider: ^6.1.2
  permission_handler: ^12.0.1
  purchases_flutter: ^9.10.7
  purchases_ui_flutter: ^9.10.7
  recase: ^4.1.0
  riverpod_annotation: ^4.0.1
  sentry_flutter: ^9.10.0
  share_plus: ^12.0.1
  sign_in_with_apple: ^6.1.4
  shared_preferences: ^2.5.4
  shimmer: ^3.0.0
  sliver_tools: ^0.2.12
  smooth_page_indicator: ^2.0.1
  sqlite3_flutter_libs: ^0.5.28
  supabase_auth_ui: ^0.5.5
  supabase_flutter: ^2.12.0
  table_calendar: ^3.2.0
  timezone: ^0.10.0
  url_launcher: ^6.3.2
  uuid: ^4.5.2
  visibility_detector: ^0.4.0+2
  fl_chart: ^1.1.1
  flex_color_scheme: ^8.2.0
  app_settings: ^7.0.0
  timeago: ^3.7.1

  riverpod: any
dev_dependencies:
  build_runner: ^2.10.5
  custom_lint: ^0.8.1
  drift_dev: ^2.22.2
  flutter_gen_runner: ^5.12.0
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  go_router_builder: ^4.1.3
  json_serializable: ^6.11.3
  mocktail: ^1.0.4
  riverpod_generator: ^4.0.2
  riverpod_lint: ^3.1.2
  sentry_dart_plugin: ^3.2.1
  very_good_analysis: ^10.0.0

dependency_overrides:
  analyzer: ^9.0.0
  dart_style: 3.1.3
  email_validator: ^3.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - env/.env.development
    - env/.env.staging
    - env/.env.production
